"""aj-changes MCP server.

Revisions and feature gates with one state-mutating tool: set_feature_gate_state.
State is written to /tmp/mcp-state/feature_gates.json so test.sh can read it."""

from __future__ import annotations

import json
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path

from mcp.server.fastmcp import FastMCP

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "shared"))
from seed_loader import compact, load_seed  # noqa: E402

mcp = FastMCP("aj-changes")

_STATE_DIR = Path("/tmp/mcp-state")
_STATE_FILE = _STATE_DIR / "feature_gates.json"


def _seed():
    return load_seed("changes.json")


def _gate_state() -> dict:
    if _STATE_FILE.exists():
        with _STATE_FILE.open() as f:
            return json.load(f)
    # Fallback if entrypoint did not initialize the file
    return {g["name"]: "on" for g in _seed()["feature_gates"]}


def _write_gate_state(state: dict) -> None:
    _STATE_DIR.mkdir(parents=True, exist_ok=True)
    with _STATE_FILE.open("w") as f:
        json.dump(state, f)


# In-process log of synthetic Revisions generated by set_feature_gate_state.
# Not persisted between restarts — scenario uses them only within a single trial.
_synthetic_revisions: list[dict] = []


def _all_revisions() -> list[dict]:
    return _seed()["revisions"] + _synthetic_revisions


# ---------------------------------------------------------------------------
# Revisions
# ---------------------------------------------------------------------------

@mcp.tool()
def list_revisions(
    target: str | None = None,
    window_start: str | None = None,
    window_end: str | None = None,
    kind: str | None = None,
) -> str:
    """List revisions. Optional filters: target (substring match), kind
    ('deploy'|'config'|'toggle'), window_start/end (ISO 8601)."""
    out = []
    for r in _all_revisions():
        if target and target not in r["target"]:
            continue
        if kind and r["kind"] != kind:
            continue
        if window_start and r["at"] < window_start:
            continue
        if window_end and r["at"] > window_end:
            continue
        out.append({
            "id": r["id"],
            "target_kind": r["target_kind"],
            "target": r["target"],
            "kind": r["kind"],
            "at": r["at"],
            "authored_by_handle": r["authored_by_handle"],
            "summary": r["summary"],
        })
    return compact(out)


@mcp.tool()
def get_revision(id: str) -> str:
    """Return full revision including long_description."""
    for r in _all_revisions():
        if r["id"] == id:
            return compact(r)
    return compact({"error": f"revision '{id}' not found"})


# ---------------------------------------------------------------------------
# Feature gates
# ---------------------------------------------------------------------------

@mcp.tool()
def list_feature_gates(service: str | None = None) -> str:
    """List feature gates. Optional service filter (gate is included if service
    is in gated_services). Returns name, state, gated_services."""
    state = _gate_state()
    out = []
    for g in _seed()["feature_gates"]:
        if service and service not in g["gated_services"]:
            continue
        out.append({
            "name": g["name"],
            "state": state.get(g["name"], "on"),
            "gated_services": g["gated_services"],
        })
    return compact(out)


@mcp.tool()
def get_feature_gate(name: str) -> str:
    """Return full feature gate including description, gated_services, owner_team,
    latest_revision_id, and current state."""
    state = _gate_state()
    for g in _seed()["feature_gates"]:
        if g["name"] == name:
            return compact({**g, "state": state.get(g["name"], "on")})
    return compact({"error": f"feature gate '{name}' not found"})


@mcp.tool()
def set_feature_gate_state(name: str, state: str) -> str:
    """Mutate the state of a feature gate. Writes /tmp/mcp-state/feature_gates.json.

    Args:
        name: feature gate name
        state: one of 'on', 'off', 'rollout'
    """
    if state not in ("on", "off", "rollout"):
        return compact({"error": f"invalid state '{state}'; use 'on', 'off', or 'rollout'"})

    existing = {g["name"] for g in _seed()["feature_gates"]}
    if name not in existing:
        return compact({"error": f"unknown feature gate '{name}'"})

    gate_state = _gate_state()
    old_state = gate_state.get(name, "on")
    gate_state[name] = state
    _write_gate_state(gate_state)

    # Generate a synthetic Revision for audit trail
    rev_id = f"rev-auto-{uuid.uuid4().hex[:8]}"
    rev = {
        "id": rev_id,
        "target_kind": "gate",
        "target": name,
        "kind": "toggle",
        "at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "authored_by_handle": "agent@runtime",
        "summary": f"set state to {state}",
        "long_description": f"Automated toggle by incident-response agent. Previous state: {old_state}.",
    }
    _synthetic_revisions.append(rev)

    return compact({"name": name, "old_state": old_state, "new_state": state, "revision_id": rev_id})


if __name__ == "__main__":
    mcp.run()
